document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'./css/normalize.css\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <style>");
document.writeln("         #d1{");
document.writeln("            box-sizing: border-box;");
document.writeln("            width: 1000px;");
document.writeln("            margin: 0 auto;");
document.writeln("            width: 1000px;");
document.writeln("            height: 30px;");
document.writeln("        }");
document.writeln("        #d1>ul{");
document.writeln("            margin: 0;");
document.writeln("            display: flex;");
document.writeln("            flex-flow: row nowrap;");
document.writeln("            justify-content: left;");
document.writeln("            list-style: none;");
document.writeln("            background: #333;");
document.writeln("            position: relative;");
document.writeln("            border-radius: 3px;");
document.writeln("        }");
document.writeln("        #d1>ul>li{");
document.writeln("            flex: 0 0 10%;");
document.writeln("            text-align: center;");
document.writeln("            color: #fff;");
document.writeln("            line-height: 30px;");
document.writeln("        }");
document.writeln("        #d1>ul>li:last-child{");
document.writeln("            position: absolute;");
document.writeln("            right: 14px;");
document.writeln("        }");
document.writeln("        ul{");
document.writeln("            list-style: none;");
document.writeln("            margin: 0;");
document.writeln("            padding: 0;");
document.writeln("        }");
document.writeln("        a{");
document.writeln("            text-decoration: none;");
document.writeln("            color:#666;");
document.writeln("        }");
document.writeln("        #zhu>li>span{     ");
document.writeln("            display: block;");
document.writeln("            width: 85px;");
document.writeln("            height: 35px;");
document.writeln("            background: pink;");
document.writeln("            text-align: center; ");
document.writeln("            border-radius: 3px;   ");
document.writeln("            font: normal small-caps 400 16px \'宋体\';   ");
document.writeln("            line-height: 35px;");
document.writeln("            border-bottom: 1px dashed #888;   ");
document.writeln("            cursor: pointer;  ");
document.writeln("        }");
document.writeln("        #zhu>li>ul>li{");
document.writeln("            box-sizing: border-box;");
document.writeln("            width:85px;");
document.writeln("            height: 25px;");
document.writeln("            font: normal small-caps 400 14px \'宋体\';   ");
document.writeln("            border:1px solid #e6e6e6;");
document.writeln("            line-height: 25px;  ");
document.writeln("            border-radius:3px;");
document.writeln("            text-align: center;");
document.writeln("            line-height: 25px;");
document.writeln("        }");
document.writeln("        span+ul{");
document.writeln("            display: none;");
document.writeln("        }");
document.writeln("        .xianshi{");
document.writeln("            display: block;");
document.writeln("        }");
document.writeln("        #zong{");
document.writeln("            margin: 0 auto;");
document.writeln("            width: 1000px;");
document.writeln("        }");
document.writeln("        #zong>#d1,#zong>#zhu{");
document.writeln("            float: left;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
// document.writeln("    <div id=\'zong\'>");
document.writeln("       <div id=\'d1\'>");
document.writeln("        <ul>");
document.writeln("            <li>XXXXX</li>");
document.writeln("            <li>XXXXX</li>");
document.writeln("            <li>XXXXX</li>");
document.writeln("            <li>后台操作</li>");
document.writeln("        </ul> ");
document.writeln("    </div>  ");
document.writeln("    <ul id=\'zhu\'>");
document.writeln("        <li>");
document.writeln("           <span>网址导航</span>");
document.writeln("           <ul class=\'xianshi\'>");
document.writeln("               <li><a href=\'dhzl_create.html\' target=\'a\' >添加dhzl</a></li>");
document.writeln("               <li><a href=\'dhzl_list.html\'>dhzl列表</a></li>");
document.writeln("               <li><a href=\'wz_create.html\'>添加网址</a></li>");
document.writeln("               <li><a href=\'wz_list.html\'>网址列表</a></li>");
document.writeln("           </ul>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("            <span>电影推荐</span>");
document.writeln("           <ul>");
document.writeln("               <li><a href=\'dytj_create.html\'>添加电影</a></li>");
document.writeln("               <li><a href=\'dytj_list.html\'>电影列表</a></li>");
document.writeln("           </ul>");
document.writeln("        </li>");
document.writeln("        <li>");
document.writeln("            <span>学习笔记</span>");
document.writeln("            <ul>");
document.writeln("                <li><a href=\'xxbj_create.html\'>添加笔记</a></li>");
document.writeln("                <li><a href=\'xxbj_list.html\'>笔记列表</a></li>");
document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("     </ul>");
// document.writeln("    </div> ");
document.writeln("     <script>");
document.writeln("         var zhu=document.getElementById(\'zhu\');");
document.writeln("         var spans=zhu.getElementsByTagName(\'span\');");
document.writeln("         console.log(spans);");
document.writeln("         for(var span of spans){");
document.writeln("             span.onclick=function(){");
document.writeln("                 var xianshi=zhu.querySelector(\'#zhu>li>ul.xianshi\');");
document.writeln("                 this.nextElementSibling.className=\'xianshi\';");
document.writeln("                 if(xianshi!=null){");
document.writeln("                     xianshi.className=\'\';");
document.writeln("                 }");
document.writeln("             }");
document.writeln("         }");
document.writeln("         ");
document.writeln("     </script>");
document.writeln("</body>");
document.writeln("</html>");