document.writeln(" <div id=\'contain\'>");
document.writeln("        <h3>yu网么?</h3>");
document.writeln("        <ul class=\'xs\'>");
document.writeln("            <li><a href=\'wz.html\'>网址导航</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>电影推荐</a></li>");
document.writeln("            <li><a href=\'bj.html\'>笔记分享</a></li>");
document.writeln("        </ul>");
document.writeln("        <button>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("        </button>");
document.writeln("    </div>");
document.writeln("    <script>");
document.writeln("        var button=document.getElementsByTagName(\'button\')[0];");
document.writeln("        console.log(button);");
document.writeln("        button.onclick=function(){");
document.writeln("            var ul=document.getElementsByTagName(\'ul\')[0];");
document.writeln("            console.log(ul);");
document.writeln("            if(ul.className!==\'\'){");
document.writeln("                ul.className=\'\';");
document.writeln("            }else{");
document.writeln("                ul.className=\'xs\';");
document.writeln("            }");
document.writeln("            ");
document.writeln("        }");
document.writeln("    </script>");
document.writeln("");