document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <style>");
document.writeln("        @media(min-width:992px){");
document.writeln("        /* 注册登录 */");
document.writeln("        ul.xs>li:nth-child(4){");
document.writeln("           margin-left: 1020px;");
document.writeln("        }");
document.writeln("      #d1,#d2{");
document.writeln("          padding: 12px 5px !important;");
document.writeln("      }");
document.writeln("         #contain{");
document.writeln("             width: 100%;");
document.writeln("             height: 42px;");
document.writeln("             background:#222;");
document.writeln("             border: #080808;");
document.writeln("             font-size: 14px;");
document.writeln("             color: #fff;");
document.writeln("             border-radius: 2px;");
document.writeln("         }   ");
document.writeln("        #contain h3{");
document.writeln("            float: left;");
document.writeln("            color: #9d9d9d;");
document.writeln("            margin: 0;");
document.writeln("            font: 36px;");
document.writeln("            line-height: 36px;");
document.writeln("            margin-left: 18px;");
document.writeln("            margin-right: 40px;");
document.writeln("        }");
document.writeln("        #contain ul{");
document.writeln("            float: left;");
document.writeln("            margin: 0;");
document.writeln("            padding: 0;");
document.writeln("            height: 100%;");
document.writeln("        }");
document.writeln("        ul>li{");
document.writeln("            list-style: none;");
document.writeln("            float: left;");
document.writeln("            height: 100%;");
document.writeln("        }");
document.writeln("        #contain>ul a{");
document.writeln("            box-sizing: border-box;");
document.writeln("            display: block;");
document.writeln("            text-decoration: none;");
document.writeln("            color: #9d9d9d;");
document.writeln("            text-align: center;");
document.writeln("            height: 100%;");
document.writeln("            padding: 12px 15px;");
document.writeln("        }");
document.writeln("        button{");
document.writeln("            display: none;");
document.writeln("        }");
document.writeln("    }");
document.writeln("    @media(max-width:992px){");
document.writeln("        .xs{");
document.writeln("            display: none;");
document.writeln("        }");
document.writeln("        #contain button{");
document.writeln("            box-sizing: border-box;");
document.writeln("            display: block;");
document.writeln("            /* float: right; */");
document.writeln("            position: absolute;");
document.writeln("            right: 0;");
document.writeln("            background: transparent;");
document.writeln("            border: 1px solid #9d9d9d;");
document.writeln("            border-radius: 4px;");
document.writeln("            margin-right:15px ;");
document.writeln("            padding: 8px 9px;");
document.writeln("            margin-top: 5px;");
document.writeln("        }");
document.writeln("        button .icon-bar{");
document.writeln("            display: block;");
document.writeln("            width: 22px;");
document.writeln("            height: 2px;");
document.writeln("            border-radius: 1px;");
document.writeln("            background: #fff;");
document.writeln("        }");
document.writeln("        button .icon-bar:nth-child(2){");
document.writeln("            margin: 4px 0;");
document.writeln("        }");
document.writeln("         #contain{");
document.writeln("             width: 100%;");
document.writeln("             height: 42px;");
document.writeln("             background:#222;");
document.writeln("             border: #080808;");
document.writeln("             font-size: 14px;");
document.writeln("             color: #fff;");
document.writeln("             border-radius: 2px;");
document.writeln("             position: relative;");
document.writeln("         }   ");
document.writeln("        #contain h3{");
document.writeln("            float: left;");
document.writeln("            color: #9d9d9d;");
document.writeln("            margin: 0;");
document.writeln("            font: 36px;");
document.writeln("            line-height: 36px;");
document.writeln("            margin-left: 8px;");
document.writeln("            margin-right: 10px;");
document.writeln("        }");
document.writeln("        #contain::before{");
document.writeln("            content: \'\';");
document.writeln("            display: table;");
document.writeln("        }");
document.writeln("        #contain ul{");
document.writeln("            /* display: block; */");
document.writeln("            border-radius: 2px;");
document.writeln("            margin-top: 6px !important;");
document.writeln("            margin: 0;");
document.writeln("            padding: 0;");
document.writeln("            float: left;");
document.writeln("            width: 100%;");
document.writeln("            height: 140px;");
document.writeln("            /* position: absolute; */");
document.writeln("            top: 28px;");
document.writeln("            background-image: linear-gradient(to right,#f1b1ee,#83c0f1);");
document.writeln("        }");
document.writeln("        #contain ul li{");
document.writeln("            list-style: none;");
document.writeln("            padding: 4px 5px;");
document.writeln("            width: 64px;");
document.writeln("        }");
document.writeln("        #contain a{");
document.writeln("            text-decoration: none;");
document.writeln("            color: #e66cdf;");
document.writeln("        }");
document.writeln("          ");
document.writeln("    }");
document.writeln("   ");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div id=\'contain\'>");
document.writeln("        <h3>yu网么?</h3>");
document.writeln("        <ul class=\'xs\'>");
document.writeln("            <li><a href=\'wz.html\'>网址导航</a></li>");
document.writeln("            <li><a href=\'javascript:;\'>电影推荐</a></li>");
document.writeln("            <li><a href=\'bj.html\'>笔记分享</a></li>");
document.writeln("            <li><a id=\'d1\' href=\'reg.html\'>注册</a></li>");
document.writeln("            <li><a id=\'d2\' href=\'login.html\'>登录</a></li>");
document.writeln("        </ul>");
document.writeln("        <button>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("        </button>");
document.writeln("    </div>");
document.writeln("    <script>");
document.writeln("        var button=document.getElementsByTagName(\'button\')[0];");
document.writeln("        console.log(button);");
document.writeln("        button.onclick=function(){");
document.writeln("            var ul=document.getElementsByTagName(\'ul\')[0];");
document.writeln("            console.log(ul);");
document.writeln("            if(ul.className!==\'\'){");
document.writeln("                ul.className=\'\';");
document.writeln("            }else{");
document.writeln("                ul.className=\'xs\';");
document.writeln("            }");
document.writeln("            ");
document.writeln("        }");
document.writeln("    </script>");
document.writeln("</body>");
document.writeln("</html>");